FROM nvidia/cuda:12.9.1-cudnn-devel-ubuntu24.04

RUN apt update && apt install -y build-essential python3-dev python-is-python3 python3-pip

RUN python -m pip install -r requirements.txt --break-system-packages